

// Highlight Projects
export const projects = [
    {
        title: "Cyberpunk Portfolio",
        description: "A futuristic portfolio website with a hacker aesthetic.",
        techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
        thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
        liveDemo: "https://example.com",
        repo: "https://github.com/meranHM/my-website",
        featured: true,
        tag: "Portfolio",
        video: "/images/cyberpunk-portfolio.png",
        category: "Portfolio"
    },
    {
        title: "SaaS Dashboard",
        description: "A neatly design SaaS dashboard",
        techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
        thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
        liveDemo: "https://example.com",
        repo: "https://github.com/meranHM/my-website",
        featured: true,
        tag: "saas",
        video: "/projects/cyberpunk-portfolio/thumbnail.png",
        category: "SaaS"
    },
    {
        title: "Vanta Boutique",
        description: "A classy and modern E-commerce website",
        techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
        thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
        liveDemo: "https://example.com",
        repo: "https://github.com/meranHM/my-website",
        featured: true,
        tag: "ecommerce",
        video: "/projects/cyberpunk-portfolio/thumbnail.png",
        category: "Ecommerce"
    },
    {
        title: "Admin Panel",
        description: "A modern and clean admin panel",
        techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
        thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
        liveDemo: "https://example.com",
        repo: "https://github.com/meranHM/my-website",
        featured: true,
        tag: "dashboards",
        video: "/projects/cyberpunk-portfolio/thumbnail.png",
        category: "Dashboards"
    },
    {
        title: "Task Management App",
        description: "A handy and interactive to-do list App",
        techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
        thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
        liveDemo: "https://example.com",
        repo: "https://github.com/meranHM/my-website",
        featured: true,
        tag: "webapp",
        video: "/projects/cyberpunk-portfolio/thumbnail.png",
        category: "WebApps"
    },
    {
        title: "Landing Page",
        description: "A unique and elegant landing page",
        techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
        thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
        liveDemo: "https://example.com",
        repo: "https://github.com/meranHM/my-website",
        featured: true,
        tag: "landing",
        video: "/projects/cyberpunk-portfolio/thumbnail.png",
        category: "Landing Page"
    },
]



// All Projects
export const projectsObj = {
    portfolio: [
        {
            title: "Cyberpunk Portfolio",
            description: "A futuristic portfolio website with a hacker aesthetic.",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/images/cyberpunk-portfolio.png",
        },
        {
            title: "Cyberpunk Portfolio",
            description: "A futuristic portfolio website with a hacker aesthetic.",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/images/cyberpunk-portfolio.png",
        },
        {
            title: "Cyberpunk Portfolio",
            description: "A futuristic portfolio website with a hacker aesthetic.",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/images/cyberpunk-portfolio.png",
        },
    ],
    saas: [
        {
            title: "SaaS Dashboard",
            description: "A neatly design SaaS dashboard",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
        {
            title: "SaaS Dashboard",
            description: "A neatly design SaaS dashboard",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
        {
            title: "SaaS Dashboard",
            description: "A neatly design SaaS dashboard",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
    ],
    ecommerce: [
        {
            title: "Vanta Boutique",
            description: "A classy and modern E-commerce website",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
        {
            title: "Vanta Boutique",
            description: "A classy and modern E-commerce website",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
        {
            title: "Vanta Boutique",
            description: "A classy and modern E-commerce website",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
    ],
    dashboards: [
        {
            title: "Admin Panel",
            description: "A modern and clean admin panel",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
        {
            title: "Admin Panel",
            description: "A modern and clean admin panel",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
        {
            title: "Admin Panel",
            description: "A modern and clean admin panel",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
    ],
    webapps: [
        {
            title: "Task Management App",
            description: "A handy and interactive to-do list App",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
        {
            title: "Task Management App",
            description: "A handy and interactive to-do list App",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
        {
            title: "Task Management App",
            description: "A handy and interactive to-do list App",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
    ],
    landings: [
        {
            title: "Landing Page",
            description: "A unique and elegant landing page",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
        {
            title: "Landing Page",
            description: "A unique and elegant landing page",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
        {
            title: "Landing Page",
            description: "A unique and elegant landing page",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
    ],
    fun: [
        {
            title: "CSS/JS Animation",
            description: "A unique and fun UI",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
        {
            title: "CSS/JS Animation",
            description: "A unique and fun UI",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
        {
            title: "CSS/JS Animation",
            description: "A unique and fun UI",
            techStack: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
            thumbnail: "/projects/cyberpunk-portfolio/thumbnail.png",
            liveDemo: "https://example.com",
            repo: "https://github.com/meranHM/my-website",
            video: "/projects/cyberpunk-portfolio/thumbnail.png",
        },
    ],
}
