import type { Metadata } from "next"
import { JetBrains_Mono, Orbitron, Press_Start_2P } from "next/font/google"
import "./globals.css"
import ClientLayout from "@/components/ClientLayout"


const jetBrains = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  style: ["normal", "italic"],
  variable: "--font-mono",
})

const orbitron = Orbitron({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-orbit",
})

const pressStart2P = Press_Start_2P({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-press-start",
})


export const metadata: Metadata = {
  title: "Mehran Shahani",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrains.variable} ${orbitron.variable} ${pressStart2P.variable} antialiased`}
      >
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
